"""Add llm_raw_response column

Revision ID: 78dff5c64e12
Revises: 0db4c622cfa9
Create Date: 2026-06-10 00:32:48.427263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dff5c64e12'
down_revision: Union[str, None] = '0db4c622cfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('llm_raw_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'llm_raw_response')
    # ### end Alembic commands ###
